---
packages_dnf:
  - vim
  - htop
  - curl
  - wget
  - ncdu
  - tree
  - apt-transport-https
  - ca-certificates
  - openssh-server
  - gnupg
  - python3-pip
  - make
  - git
  - bash-completion
  - zsh
  - flameshot
  - plocate
  - jq
  - mtr
  - vlc
  - bat
  - neofetch
  - btop
  - httpie
  - vagrant
  - solaar
  - direnv
  - gnome-tweaks

packages_rpm:
  - https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom-0.9.6-1.x86_64.rpm
  - https://github.com/derailed/k9s/releases/download/v0.31.8/k9s_linux_amd64.rpm
