---
- name: Install packages
  tags: packages
  block:
    - name: Install Fedora packages
      become: true
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: present
      loop: "{{ packages_dnf }}" # install packages one by one
        # - "{{ apt_packages }}" # install all packages at once

    - name: Install Fedora packages from source
      become: true
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: present
        disable_gpg_check: true
      loop: "{{ packages_rpm }}"

    - name: Enable and start services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - sshd
