---
  - block:
    - name: Install Google Key
      become: true
      apt_key:
        url: 'https://dl.google.com/linux/linux_signing_key.pub'
        state: present

    - name: Install Google Repository
      become: true
      apt_repository:
        repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
        state: present
        filename: google-chrome

    - name: Install Google Chrome
      become: true
      apt:
        name: google-chrome-stable
        update_cache: true

    tags: chrome

  - block:
    - name: Install Brave Key
      become: true
      apt_key:
        url: 'https://brave-browser-apt-release.s3.brave.com/brave-core.asc'
        state: present

    - name: Install Brave Repository
      become: true
      apt_repository:
        repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present
        filename: brave

    - name: Install Brave Browser
      become: true
      apt:
        name: brave-browser

    tags: brave