---
- block:
  - name: Add Docker GPG key
    ansible.builtin.rpm_key:
      key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

  - name: Add Docker repository
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/fedora/docker-ce.repo"
      dest: '/etc/yum.repos.d/docker-ce.repo'
      owner: root
      group: root
      mode: 0644

  - name: Install Docker
    become: true
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  - name: Adding existing user to group Docker
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user_id }}'
      groups: docker
      append: yes

  - name: Flush handlers
    meta: flush_handlers

  tags: docker
