---
- block:
  - name: Add PHP 7.4 apt repository
    become: true
    apt_repository:
      repo: ppa:ondrej/php

  - name: Install PHP 7.4 required packages
    become: true
    apt:
      name: '{{ item }}'
      update_cache: yes
      state: present
    loop:
      - "{{ php_packages }}"

  - name: Verify if composer is already installed
    command: test -f /usr/local/bin/composer
    register: composer
    ignore_errors: true

  - block:
    - name: Download script to install Composer
      become: true
      get_url:  
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Install Composer
      become: true
      command:
        cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    when: composer.rc != 0

  tags: php7.4